apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: venkat
  labels:
    app: example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: venkat
  labels:
    app: example
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

